name = "katelyatv"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# 默认 D1 数据库配置（用于命令行操作）
[[d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "875bf18c-cafc-47d4-99a9-469bdcb6da00"

# 生产环境配置
[env.production]
name = "katelyatv"

# 生产环境 D1 数据库配置
[[env.production.d1_databases]]
binding = "DB"
database_name = "katelyatv-db"
database_id = "875bf18c-cafc-47d4-99a9-469bdcb6da00"

